### ISSUE TITLE
UDAWA Actuator4CH - Tambah Screw Terminal Block

### ISSUE THREAD

**Issue by iwas108** [NarinLab/Udawa#3]
Pada issue ini main tasknya adalah menambahkan koneksi ke modul relay 4 Channel.
![Gambar modul relay 4 ch](https://components101.com/sites/default/files/component_pin/Four-Channel-Relay-Module-Pinout.jpg)

Relay 4 Channel punya 4 pin input (INx atau pada gambar diagram Cx). 4 Pin input ini dipetakan ke pin ESP32 yang telah dicek terlebih dahulu untuk memastikan pin tersebut tidak menimbulkan masalah jika digunakan (search: ESP32 usable pin). Masing-masing dimulai dari **C1 hingga C4: D32, D33, D25, D26**. Pin GND dan pin 5V disambungkan ke pin yang sama.

![Gambar diagram Actuator4Ch](https://raw.githubusercontent.com/NarinLab/Udawa/main/Hardware/UDAWA-Aktuator4CH/Wiring%20-%20Actuator4CH.svg)

Untuk bagian tegangan tinggi (listrik PLN) yang akan mentenagai beban, sebelum masuk ke terminal block **~RCx** yang akan mengarah ke modul relay, ditambahkan fuse holder (rumah skring) kaca silinder sebagai pengaman. Kemudian, kabel ini akan masuk ke bagian **Common** dari masing-masing relay. Kabel yang satunya lagi keluar dari terminal NO (**Normally Open**) menuju ke PCB dan masuk di terminal **~NOx**. Dari terminal **~NOx**, daya listrik tegangan tinggi akan disambungkan oleh jalur tegangan tinggi PCB ke terminal akhir tempat dimana stop kontak akan disambungkan (**CHx**).

### To Do
1. Tambahkan pada skematik untuk terminal 220V (2 block x 1)
2. Tambahkan pada skematik untuk terminal AC/DC (2 block x 1)
3. Tambahkan pada skematik untuk terminal control relay (Cx + VCC + GND) (2 block x 3)
4. Tambahkan pada skematik untuk fuse holder (4 unit)
5. Tambahkan pada skematik untuk terminal block ~RCx (2 block x 2)
6. Tambahkan pada skematik untuk terminal block ~NOx (2 block x 2)
7. Tambahkan pada skematik untuk terminal block stop kontak CHx (2 block x 4)
8. Lakukan wiring pada mode board dan pastikan penamaan setiap pin dan konektor dibuat dengan jelas dan rapi sesuai diagram.

### Pembagian tugas
Pembagian tugas saya serahkan ke masing-masing tim leader, untuk penamaan branch pekerjaan saya bebaskan asal mengikuti aturan common sense sehingga jelas dan mudah untuk dimengerti. Untuk detail diskusi seperti nama part silahkan diskusi di issue ini agar terdokumentasi dengan baik untuk di masa depan, dan orang umum juga bisa melihat.

Tim leader juga bisa membuat issue tambahan sendiri untuk meassign rekannya tugas terkait. Ingat untuk menambahkan project di sidebar kanan halaman, gunakan projek sesuai issue yang sedang dikerjakan. Misalnya issue ini terkait dengan hardware pada varian Actuator4CH, maka project yang dikaitkan adalah HW-Actuator-4CH. Untuk label bisa gunakan **enhancement** untuk pengerjaan fitur baru.

**Comment by iwas108** [comment]
Untuk screw terminal gunakan yang 2 block, ini berhubungan dengan procurement (pengadaan/pembelian) komponen, usahakan komponen dibeli serempak/sejenis jika memungkinkan untuk menghemat cost. Misal, jika pada diagram ada 6 pin, maka gunakan 3 screw terminal 2 block.

**Comment by iwas108** [comment]
Untuk fuse holder, tolong dibantu untuk mencarikan part number yang cocok di eagle. Kita gunakan model Fuse Holder PCB Mount 5x20 seperti ini:
![Fuse Holder 5x20](https://cf.shopee.co.id/file/8e46978fb42574ecd95863e97ddb38b4)

**Comment by artawiguna** [comment]
selamat malam pak, ijin bertanya untuk relaynya 2 block x3 itu jadinya 6 ya pak... kalau sesuai di diagram ada 4 pak, jadinya pakai yang mana pak?

**Comment by iwas108** [comment]
> selamat malam pak, ijin bertanya untuk relaynya 2 block x3 itu jadinya 6 ya pak... kalau sesuai di diagram ada 4 pak, jadinya pakai yang mana pak?

Maksudnya jika ada 6 pin (contoh pin control yg warna hijau + 2 pin untuk power) yang akan dipasangkan terminal block, maka kita gunakan terminal block 2 pin sebanyak 3 buah. Atau biar tidak ruwet, semua pin kita gunakan terminal block 2 pin (**W237-102**). 

Untuk fuse holder sudah ketemu: http://www.diymodules.org/eagle-show-object?type=std&file=fuse.lbr&package=FUSE_HOLDER_5X20MM

Tolong dibantu untuk download dan tambah library tersebut ke folder library.

**Comment by artawiguna** [comment]
kemudian  terminal 220V di tambahkan dimananya pak?
soalnya kalo ga salah di eagle sudah di tambahkan pak

**Comment by iwas108** [comment]
> kemudian terminal 220V di tambahkan dimananya pak?
> soalnya kalo ga salah di eagle sudah di tambahkan pak

Terminal yg sudah ada tidak perlu ditambahkan lagi, itu hanya untuk melengkapi diagram saja

**Comment by artawiguna** [comment]
> semua

oww jadi pin nya ada 6 yaa pak... maaf saya kira tadi relaynya 6 ch

**Comment by iwas108** [comment]
> > semua
> 
> oww jadi pin nya ada 6 yaa pak... maaf saya kira tadi relaynya 6 ch

Yes, Pin relay 4 channel punya 6 pin,4 untuk kontrol (C1, C2, C3, C4), dan dua untuk power (5V dan GND).

**Comment by artawiguna** [comment]
malam pak ijin bertanya kembali untuk penamaan setiap pin tidak bisa sesuai dengan diagram karena pin yang kedua menyesuaikan valuenya dengan pin yang pertama, mohon arahannya
terimakasih
![image](https://user-images.githubusercontent.com/57532508/132704370-3d66c089-5839-4019-b96f-68aaae819f8e.png)

**Comment by iwas108** [comment]
> malam pak ijin bertanya kembali untuk penamaan setiap pin tidak bisa sesuai dengan diagram karena pin yang kedua menyesuaikan valuenya dengan pin yang pertama, mohon arahannya
> terimakasih
> ![image](https://user-images.githubusercontent.com/57532508/132704370-3d66c089-5839-4019-b96f-68aaae819f8e.png)

Coba di samain saja namamya, NO12, NO34.. untuk nama wire/label pastikan sama agar terhubung

**Comment by artawiguna** [comment]
> > malam pak ijin bertanya kembali untuk penamaan setiap pin tidak bisa sesuai dengan diagram karena pin yang kedua menyesuaikan valuenya dengan pin yang pertama, mohon arahannya
> > terimakasih
> > ![image](https://user-images.githubusercontent.com/57532508/132704370-3d66c089-5839-4019-b96f-68aaae819f8e.png)
> 
> Coba di samain saja namamya, NO12, NO34.. untuk nama wire/label pastikan sama agar terhubung

baik siap pak

**Comment by artawiguna** [comment]
Selamat pagi pak ijin bertanya untuk GND dan 5V yang dari HLK boleh di pindah pak?
soalnya Relaynya jauh jadinya ngambil GND dan 5V... maksunya itu di switch

![image](https://user-images.githubusercontent.com/57532508/133013363-ff74235f-fd62-42cf-b278-c8bd21c39e90.png)

**Comment by iwas108** [comment]
Slamat pagi, dipindah saja yg penting efisien dan pikirkan nanti kemudahannya untuk mengakses komponen

**Comment by artawiguna** [comment]
> Slamat pagi, dipindah saja yg penting efisien dan pikirkan nanti kemudahannya untuk mengakses komponen
baik siap pak
