### ISSUE TITLE
UDAWA Sensor Water - Tambah Komponen Utama

### ISSUE THREAD

**Issue by iwas108** [NarinLab/Udawa#6]
Pekerjaan besar untuk tim yang mengerjakan HW Sensor varian water sensor (TDS dan Water Temperature). Untuk diagram pengkabelan dibuat seperti berikut:

![Diagram HW Sensor TDS & Temp](https://raw.githubusercontent.com/NarinLab/Udawa/main/Hardware/UDAWA-SensorWater/Wiring%20-%20SensorWater.svg)

### To do
1. Tambahkan komponen Arduino Nano
2. Tambahkan komponen Logic Level Converter
3. Tambahkan Terminal Block untuk koneksi ke Sensor TDS dan Sensor DS18B20
3. Lakukan Wiring sesuai diagram
4. Lakukan Routing pada mode board

### Pengerjaan
Tim leader bisa bagi tugas kepada rekannya yang lain, nama branch saya bebaskan asal sesuai common sense dan mudah dimengerti. Semua diskusi terkait issue silahkan diskusikan disini sebagai dokumentasi.

**Comment by WidiaPrasetia** [comment]
Selamat malam pak, 
Saya stuck di To Do no 3
![Screenshot_3](https://user-images.githubusercontent.com/56190478/132952298-843fa720-589d-430f-a7b4-b70c8c30143b.jpg)
Mohon petunjuknya untuk gambar yang saya kirimkan ini pak. Terima kasih

**Comment by iwas108** [comment]
Pakai part resistor pras,rubah nilainya (value) sesuai gambar. Pakai jenis resistor through hole

**Comment by WidiaPrasetia** [comment]
untuk penambahan terminal block untuk koneksi ke sensor ditambahkan di sebelah mana ya pak? karena digambar saya lihat semua langsung nyambung. maaf kalau ada keliru pak

**Comment by iwas108** [comment]
> untuk penambahan terminal block untuk koneksi ke sensor ditambahkan di sebelah mana ya pak? karena digambar saya lihat semua langsung nyambung. maaf kalau ada keliru pak

Di bagian sensornya. Anggap sensor itu terminal block.

**Comment by pande34** [comment]
ijin bertanya Pak Adit untuk kabelnya ngga boleh ditumpuk pak?

**Comment by pande34** [comment]
<img width="422" alt="Capture" src="https://user-images.githubusercontent.com/57532456/133741904-42159741-07f9-467b-8bfe-0086b27b5abd.PNG">

**Comment by iwas108** [comment]
routing nya tidak boleh di tumpuk, itu tantangannya saat merouting dan mengatur tata letak, bagaimana caranya agar jalur data / power tidak saling bertabrakan atau bersentuhan.

Solusi akhir juga terlalu rumit, bisa gunakan vias pada sisi bottom. Bisa cari di youtube cara menggunakan vias di eagle untuk menambahkan jalur biru (bawah).
