### ISSUE TITLE
Firmware - Init PlatformIO Untuk SensorWater-Nano

### ISSUE THREAD

**Issue by iwas108** [NarinLab/Udawa#9]
Lakukan inisialisasi firmware untuk projek SensorWater-Nano dengan PlatformIO (Pio). Detail projek yang diinisialisasi adalah:

1. Nama Projek: SensorWater-Nano
2. Jenis Framework: Arduino
3. Jenis Board: nanoatmega328new
4. Tambahkan library: ArduinoJson, StreamUtils, TaskManagerIO, OneWire, DallasTemperature

Sehingga folder Pio untuk Actuator4CH-ESP32 menjadi: Firmware/SensorWater-Nano

**Comment by WidiaPrasetia** [comment]
Selamat siang pak, saya mau bertanya pak. @iwas108 
Untuk kalimat ini "Sehingga folder Pio untuk Actuator4CH-ESP32 menjadi: Firmware/SensorWater-Nano" bagaimana maksudnya ya pak? Apakah ganti nama foldernya/buat project baru di PIO atau bagaimana pak?
Mohon arahannya pak, maaf saya sedikit bingung

**Comment by iwas108** [comment]
> Selamat siang pak, saya mau bertanya pak. @iwas108
> Untuk kalimat ini "Sehingga folder Pio untuk Actuator4CH-ESP32 menjadi: Firmware/SensorWater-Nano" bagaimana maksudnya ya pak? Apakah ganti nama foldernya/buat project baru di PIO atau bagaimana pak?
> Mohon arahannya pak, maaf saya sedikit bingung

Pas buat projek, buat nama projeknya sesuai nama folder, dan lokasi projek taruh di dalam folder Firmware. Contohnya sama seperti yg saya init untuk firmware bagian Actuator4CH
